### ISSUE TITLE
Presets: '.json.mozlz4' or '.json' filename extension at save time 

### ISSUE THREAD

**Issue by grahamperrin** [serj-kzv/mozlz4-edit#2]
## Observation

The file _Open_ dialogue (in response to a click on either _Browse …_ button) is preset to seek `.json.mozlz4` or `.json` files.

## Enhancement request

The _Save as …_ button should result in routine that will automatically append the appropriate extension to the name of the file

- maybe with the extension apparent in the _Save_ dialogue. 

Please, is that possible?

**Comment by serj-kzv** [comment]
fixed
