### ISSUE TITLE
Suggest adding link to Addon's AMO URL on GitHub Repo

### ISSUE THREAD

**Issue by Grossdm** [serj-kzv/mozlz4-edit#4]
Hello,

I think it would be helpful to add a link to your addon's [AMO page](https://addons.mozilla.org/addon/mozlz4-edit/) either to your GitHub repo's Readme file and/or the repo description/header.

I think the "generic" AMO URL https://addons.mozilla.org/addon/mozlz4-edit/ is best to use (vs. one with "/en-US/firefox/", for example) because AMO redirects to the user agent's language and platform.

Kind regards,

Doug®

**Comment by serj-kzv** [comment]
fixed
